name: GitHub Actions Demo

on:
  push:
    branches: 
      - main
    paths-ignore: 
      - .github/*
  pull_request_target:
    branches: 
      - main
  schedule:
    - cron: "15 6 * * SUN"
  workflow_dispatch:
   inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true 
    
